import dotenv from "dotenv";

dotenv.config();

const {
  MONGODB_USERS_USER,
  MONGODB_USERS_PASSWORD,
  MONGODB_USERS_ADDRESS,
  MONGODB_USERS_DATABASE,
  MONGODB_SYNAPSE_USER,
  MONGODB_SYNAPSE_PASSWORD,
  MONGODB_SYNAPSE_ADDRESS,
  MONGODB_SYNAPSE_DATABASE,
  MONGODB_TRAME_USER,
  MONGODB_TRAME_PASSWORD,
  MONGODB_TRAME_ADDRESS,
  MONGODB_TRAME_DATABASE,
  MONGODB_ODYSSEE_USER,
  MONGODB_ODYSSEE_PASSWORD,
  MONGODB_ODYSSEE_ADDRESS,
  MONGODB_ODYSSEE_DATABASE,
} = process.env;

const requiredVars = {
  MONGODB_USERS_USER,
  MONGODB_USERS_PASSWORD,
  MONGODB_USERS_ADDRESS,
  MONGODB_USERS_DATABASE,
  MONGODB_SYNAPSE_USER,
  MONGODB_SYNAPSE_PASSWORD,
  MONGODB_SYNAPSE_ADDRESS,
  MONGODB_SYNAPSE_DATABASE,
  MONGODB_TRAME_USER,
  MONGODB_TRAME_PASSWORD,
  MONGODB_TRAME_ADDRESS,
  MONGODB_TRAME_DATABASE,
  MONGODB_ODYSSEE_USER,
  MONGODB_ODYSSEE_PASSWORD,
  MONGODB_ODYSSEE_ADDRESS,
  MONGODB_ODYSSEE_DATABASE,
};

for (const [key, value] of Object.entries(requiredVars)) {
  if (!value) throw new Error(`Variable MongoDB manquante dans .env : ${key}`);
}

export const config = {
  mongodbUsers: {
    uri: `mongodb+srv://${MONGODB_USERS_USER}:${MONGODB_USERS_PASSWORD}@${MONGODB_USERS_ADDRESS}`,
    dbName: MONGODB_USERS_DATABASE,
  },
  mongodbSynapse: {
    uri: `mongodb+srv://${MONGODB_SYNAPSE_USER}:${MONGODB_SYNAPSE_PASSWORD}@${MONGODB_SYNAPSE_ADDRESS}`,
    dbName: MONGODB_SYNAPSE_DATABASE,
  },
  mongodbTrame: {
    uri: `mongodb+srv://${MONGODB_TRAME_USER}:${MONGODB_TRAME_PASSWORD}@${MONGODB_TRAME_ADDRESS}`,
    dbName: MONGODB_TRAME_DATABASE,
  },
  mongodbOdyssee: {
    uri: `mongodb+srv://${MONGODB_ODYSSEE_USER}:${MONGODB_ODYSSEE_PASSWORD}@${MONGODB_ODYSSEE_ADDRESS}`,
    dbName: MONGODB_ODYSSEE_DATABASE,
  },
  server: {
    port: process.env.PORT,
    env: process.env.NODE_ENV,
  },
  cors: {
    origin: process.env.CORS_ORIGIN,
  },
  rateLimit: {
    windowMs: parseInt(process.env.RATE_LIMIT_WINDOW_MS),
    max: parseInt(process.env.RATE_LIMIT_MAX_REQUESTS),
  },
};
